services:
  - type: web
    name: speakai
    runtime: docker
    repo: https://github.com/mypy125/speak-ai
    branch: main
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: JPRO_PORT
        value: 8080
      - key: JPRO_HOST
        value: 0.0.0.0
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /app/google-credentials.json
      - key: JAVA_OPTS
        value: "--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED --add-opens=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED --add-opens=javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED --add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED -Djava.awt.headless=true -Dprism.order=sw"
    healthCheckPath: /health
    disk:
      name: speakai-data
      mountPath: /app/data
      sizeGB: 1