ai.provider=groq

ai.api.key=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
ai.model=llama-3.1-8b-instant
ai.custom.url=
ai.temperature=0.7
ai.max.tokens=1500

speech.service.type=VOSK
speech.default.language=en
speech.api.key=

tts.type=GOOGLE


